### ISSUE TITLE
ModuleNotFoundError: No module named 'main' - Error deploying ML model using ACI

### ISSUE THREAD

**Issue by jay2017-git** [Azure/azureml-sdk-for-r#373]
I'm trying to deploy my ML model on ACI using this code. 
`
from azureml.core.webservice import AciWebservice, Webservice
from azureml.exceptions import WebserviceException

deployment_config = AciWebservice.deploy_configuration(cpu_cores=2, memory_gb=6)
aci_service_name = 'ml-model'

try:
service = Webservice(ws, name=aci_service_name)
if service:
service.delete()
except WebserviceException as e:
print()

service = Model.deploy(ws, aci_service_name, [kp_model], inference_config, deployment_config)

service.wait_for_deployment(True)
print(service.state)
`

Here is the error am getting
`
2020-08-10T11:01:28,103498848+00:00 - rsyslog/run
2020-08-10T11:01:28,109724839+00:00 - nginx/run
2020-08-10T11:01:28,111248110+00:00 - gunicorn/run
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2020-08-10T11:01:28,192849628+00:00 - iot-server/finish 1 0
2020-08-10T11:01:28,194532107+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 19.9.0
Listening at: http://127.0.0.1:31311 (18)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 42
SPARK_HOME not set. Skipping PySpark Initialization.
Exception in worker process
Traceback (most recent call last):
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
self.load_wsgi()
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
self.wsgi = self.app.wsgi()
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
return self.load_wsgiapp()
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
return util.import_app(self.app_uri)
File "/azureml-envs/azureml_d31cd964833447a6573171273c4f1235/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
import(module)
File "/var/azureml-server/wsgi.py", line 1, in
import create_app
File "/var/azureml-server/create_app.py", line 3, in
from app import main
File "/var/azureml-server/app.py", line 31, in
import main as user_main
ModuleNotFoundError: No module named 'main'
Worker exiting (pid: 42)
Shutting down: Master
Reason: Worker failed to boot.
2020-08-10T11:01:28,524618650+00:00 - gunicorn/finish 3 0
2020-08-10T11:01:28,526020716+00:00 - Exit code 3 is not normal. Killing image
`

This similar to  #350

**Comment by mx-iao** [comment]
@jay2017-git can you run [`get_webservice_logs()` ](https://azure.github.io/azureml-sdk-for-r/reference/get_webservice_logs.html) to get the logs from the deployment?

**Comment by jay2017-git** [comment]
@

> @jay2017-git can you run [`get_webservice_logs()` ](https://azure.github.io/azureml-sdk-for-r/reference/get_webservice_logs.html) to get the logs from the deployment?

@mx-iao  I did run it. That's how I got the logs above.

**Comment by jay2017-git** [comment]
@ this is the log from the init container 

`

WARNING:__main__:no config found, using configfile

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Outgoing request: Method=GET, Path=/azureml/LocalUpload/2f799dc4-b21f-4890-9f5d-e4636ee504e8/init_config.json, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.6.8; Linux 4.15.0-1092-azure)', 'x-ms-client-request-id': '25c3f802-dbe0-11ea-b0d8-d2d7e850c89f', 'x-ms-date': 'Tue, 11 Aug 2020 14:37:14 GMT', 'Authorization': 'REDACTED'}.

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Receiving Response: Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP Status Code=403, Message=This request is not authorized to perform this operation., Headers={'content-length': '246', 'content-type': 'application/xml', 'vary': 'Origin', 'server': 'Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '28548d12-e01e-006a-2dec-6f0a87000000', 'x-ms-client-request-id': '25c3f802-dbe0-11ea-b0d8-d2d7e850c89f', 'x-ms-error-code': 'AuthorizationFailure', 'date': 'Tue, 11 Aug 2020 14:37:13 GMT'}.

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:28548d12-e01e-006a-2dec-6f0a87000000Time:2020-08-11T14:37:14.3086074Z</Message></Error>.

ERROR:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Retry policy did not allow for a retry: Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:28548d12-e01e-006a-2dec-6f0a87000000Time:2020-08-11T14:37:14.3086074Z</Message></Error>.

ERROR:__main__:Init container fails with exception: Traceback (most recent call last):

  File "./download.py", line 353, in <module>

    init_container_assets(args.config_json, args.conn_string, args.container, args.appinsights_key, args.config_folder)

  File "./download.py", line 289, in init_container_assets

    downloader.download_artifact(blob_path, local_path, 0)

  File "./download.py", line 92, in download_artifact

    file_path=local_path)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2014, in get_blob_to_path

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2193, in get_blob_to_stream

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2160, in get_blob_to_stream

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 1887, in _get_blob

    operation_context=_context)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request

    HTTPError(response.status, response.message, response.headers, response.body))

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

    raise ex

azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:28548d12-e01e-006a-2dec-6f0a87000000

Time:2020-08-11T14:37:14.3086074Z</Message></Error>

 

Traceback (most recent call last):

  File "./download.py", line 353, in <module>

    init_container_assets(args.config_json, args.conn_string, args.container, args.appinsights_key, args.config_folder)

  File "./download.py", line 289, in init_container_assets

    downloader.download_artifact(blob_path, local_path, 0)

  File "./download.py", line 92, in download_artifact

    file_path=local_path)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2014, in get_blob_to_path

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2193, in get_blob_to_stream

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2160, in get_blob_to_stream

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 1887, in _get_blob

    operation_context=_context)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request

    HTTPError(response.status, response.message, response.headers, response.body))

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

    raise ex

azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:28548d12-e01e-006a-2dec-6f0a87000000

Time:2020-08-11T14:37:14.3086074Z</Message></Error>

 

 

 

 
`

**Comment by jay2017-git** [comment]
@mx-iao 

This is the log from the init container


WARNING:__main__:no config found, using configfile

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Outgoing request: Method=GET, Path=/azureml/LocalUpload/2f799dc4-b21f-4890-9f5d-e4636ee504e8/init_config.json, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.6.8; Linux 4.15.0-1092-azure)', 'x-ms-client-request-id': '25c3f802-dbe0-11ea-b0d8-d2d7e850c89f', 'x-ms-date': 'Tue, 11 Aug 2020 14:37:14 GMT', 'Authorization': 'REDACTED'}.

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Receiving Response: Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP Status Code=403, Message=This request is not authorized to perform this operation., Headers={'content-length': '246', 'content-type': 'application/xml', 'vary': 'Origin', 'server': 'Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '28548d12-e01e-006a-2dec-6f0a87000000', 'x-ms-client-request-id': '25c3f802-dbe0-11ea-b0d8-d2d7e850c89f', 'x-ms-error-code': 'AuthorizationFailure', 'date': 'Tue, 11 Aug 2020 14:37:13 GMT'}.

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:28548d12-e01e-006a-2dec-6f0a87000000Time:2020-08-11T14:37:14.3086074Z</Message></Error>.

ERROR:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Retry policy did not allow for a retry: Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:28548d12-e01e-006a-2dec-6f0a87000000Time:2020-08-11T14:37:14.3086074Z</Message></Error>.

ERROR:__main__:Init container fails with exception: Traceback (most recent call last):

  File "./download.py", line 353, in <module>

    init_container_assets(args.config_json, args.conn_string, args.container, args.appinsights_key, args.config_folder)

  File "./download.py", line 289, in init_container_assets

    downloader.download_artifact(blob_path, local_path, 0)

  File "./download.py", line 92, in download_artifact

    file_path=local_path)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2014, in get_blob_to_path

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2193, in get_blob_to_stream

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2160, in get_blob_to_stream

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 1887, in _get_blob

    operation_context=_context)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request

    HTTPError(response.status, response.message, response.headers, response.body))

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

    raise ex

azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:28548d12-e01e-006a-2dec-6f0a87000000

Time:2020-08-11T14:37:14.3086074Z</Message></Error>

 

Traceback (most recent call last):

  File "./download.py", line 353, in <module>

    init_container_assets(args.config_json, args.conn_string, args.container, args.appinsights_key, args.config_folder)

  File "./download.py", line 289, in init_container_assets

    downloader.download_artifact(blob_path, local_path, 0)

  File "./download.py", line 92, in download_artifact

    file_path=local_path)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2014, in get_blob_to_path

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2193, in get_blob_to_stream

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2160, in get_blob_to_stream

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 1887, in _get_blob

    operation_context=_context)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request

    HTTPError(response.status, response.message, response.headers, response.body))

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

    raise ex

azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:28548d12-e01e-006a-2dec-6f0a87000000

Time:2020-08-11T14:37:14.3086074Z</Message></Error>

**Comment by jay2017-git** [comment]
@mx-iao  This is the log from the init container


WARNING:__main__:no config found, using configfile

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Outgoing request: Method=GET, Path=/azureml/LocalUpload/2f799dc4-b21f-4890-9f5d-e4636ee504e8/init_config.json, Query={'snapshot': None, 'timeout': None}, Headers={'x-ms-lease-id': None, 'If-Modified-Since': None, 'If-Unmodified-Since': None, 'If-Match': None, 'If-None-Match': None, 'x-ms-range': 'bytes=0-33554431', 'x-ms-version': '2019-02-02', 'User-Agent': 'Azure-Storage/2.1.0-2.1.0 (Python CPython 3.6.8; Linux 4.15.0-1092-azure)', 'x-ms-client-request-id': '25c3f802-dbe0-11ea-b0d8-d2d7e850c89f', 'x-ms-date': 'Tue, 11 Aug 2020 14:37:14 GMT', 'Authorization': 'REDACTED'}.

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Receiving Response: Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP Status Code=403, Message=This request is not authorized to perform this operation., Headers={'content-length': '246', 'content-type': 'application/xml', 'vary': 'Origin', 'server': 'Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '28548d12-e01e-006a-2dec-6f0a87000000', 'x-ms-client-request-id': '25c3f802-dbe0-11ea-b0d8-d2d7e850c89f', 'x-ms-error-code': 'AuthorizationFailure', 'date': 'Tue, 11 Aug 2020 14:37:13 GMT'}.

INFO:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Operation failed: checking if the operation should be retried. Current retry count=0, Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:28548d12-e01e-006a-2dec-6f0a87000000Time:2020-08-11T14:37:14.3086074Z</Message></Error>.

ERROR:azure.storage.common.storageclient:Client-Request-ID=25c3f802-dbe0-11ea-b0d8-d2d7e850c89f Retry policy did not allow for a retry: Server-Timestamp=Tue, 11 Aug 2020 14:37:13 GMT, Server-Request-ID=28548d12-e01e-006a-2dec-6f0a87000000, HTTP status code=403, Exception=This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.RequestId:28548d12-e01e-006a-2dec-6f0a87000000Time:2020-08-11T14:37:14.3086074Z</Message></Error>.

ERROR:__main__:Init container fails with exception: Traceback (most recent call last):

  File "./download.py", line 353, in <module>

    init_container_assets(args.config_json, args.conn_string, args.container, args.appinsights_key, args.config_folder)

  File "./download.py", line 289, in init_container_assets

    downloader.download_artifact(blob_path, local_path, 0)

  File "./download.py", line 92, in download_artifact

    file_path=local_path)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2014, in get_blob_to_path

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2193, in get_blob_to_stream

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2160, in get_blob_to_stream

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 1887, in _get_blob

    operation_context=_context)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request

    HTTPError(response.status, response.message, response.headers, response.body))

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

    raise ex

azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:28548d12-e01e-006a-2dec-6f0a87000000

Time:2020-08-11T14:37:14.3086074Z</Message></Error>

 

Traceback (most recent call last):

  File "./download.py", line 353, in <module>

    init_container_assets(args.config_json, args.conn_string, args.container, args.appinsights_key, args.config_folder)

  File "./download.py", line 289, in init_container_assets

    downloader.download_artifact(blob_path, local_path, 0)

  File "./download.py", line 92, in download_artifact

    file_path=local_path)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2014, in get_blob_to_path

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2193, in get_blob_to_stream

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 2160, in get_blob_to_stream

    cpk=cpk)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/baseblobservice.py", line 1887, in _get_blob

    operation_context=_context)

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request

    raise ex

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/storageclient.py", line 360, in _perform_request

    HTTPError(response.status, response.message, response.headers, response.body))

  File "/usr/local/lib/python3.6/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler

    raise ex

azure.common.AzureHttpError: This request is not authorized to perform this operation. ErrorCode: AuthorizationFailure

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

RequestId:28548d12-e01e-006a-2dec-6f0a87000000

Time:2020-08-11T14:37:14.3086074Z</Message></Error>

**Comment by mx-iao** [comment]
Can you share your score.R file (you can redact any private info)

**Comment by rodrigofp-cit** [comment]
Same issue here using the python sdk
